name: Test Generated Mods

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        minecraft-version: ['1.21.1', '1.21.4']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Download npm dependencies
        run: npm install
      - name: Generate mod template
        run: npm run run -- generate --mod-name 'Test Mod' --mod-id testmod --minecraft-version ${{ matrix.minecraft-version }} --package-name net.neoforged.testmod --output-folder out
      - name: Make Gradle wrapper executable
        working-directory: ./out
        run: chmod +x gradlew
      - name: Build with Gradle
        working-directory: ./out
        run: ./gradlew build